// src/components/About.tsx
import aboutImg from '@/assets/about.jpg';

export default function About() {
    return (
        <section id="nosotros" className="scroll-mt-30 bg-gradient-to-b from-primary to-light text-accent text-center p-10">
            <h1 className="text-3xl sm:text-4xl font-bold mb-10" data-aos="zoom-in">SOBRE NOSOTROS</h1>

            <div className="flex flex-col-reverse lg:flex-row items-center gap-10">
                <div className="lg:w-1/2 text-lg sm:text-xl text-justify">
                    <p className="mb-5" data-aos="fade-up" data-aos-delay="200">
                        Pintores MDP es una empresa marplatense especializada en <strong>aplicaciones profesionales de
                            pintura, masilla y revestimientos texturados</strong>. Apostamos a la tecnología con sistemas
                        mecanizados de última generación que optimizan tiempos, mejoran la calidad y aseguran resultados
                        superiores.
                    </p>

                    <p className="mb-5" data-aos="fade-up" data-aos-delay="400">
                        Contamos con <strong>operarios calificados, legalmente habilitados y en constante
                            formación</strong>. Nos destacamos por nuestra <strong>innovación</strong>, <strong>atención
                            personalizada</strong> y <strong>comunicación clara</strong>, abordando cada proyecto con
                        compromiso, seguridad y eficiencia, con un enfoque especial en obras de gran escala o en altura.
                    </p>
                </div>

                <div className="lg:w-1/2" data-aos="fade-up" data-aos-delay="200">
                    <img src={aboutImg} alt="Sobre Nosotros" className="border-2 border-accent rounded-lg w-full" />
                </div>
            </div>
        </section>
    );
}

// src/components/About.vue
<template>
    <section id="nosotros" class="scroll-mt-30 bg-gradient-to-b from-primary to-light text-accent text-center p-10">
        <h1 class="text-3xl sm:text-4xl font-bold mb-10" data-aos="zoom-in">SOBRE NOSOTROS</h1>

        <div class="flex flex-col-reverse lg:flex-row items-center gap-10">
            <div class="lg:w-1/2 text-lg sm:text-xl text-justify">
                <p class="mb-5" data-aos="fade-up" data-aos-delay="200">
                    Pintores MDP es una empresa marplatense especializada en <strong>aplicaciones profesionales de
                        pintura, masilla y revestimientos texturados</strong>. Apostamos a la tecnología con sistemas
                    mecanizados de última generación que optimizan tiempos, mejoran la calidad y aseguran resultados
                    superiores.
                </p>

                <p class="mb-5" data-aos="fade-up" data-aos-delay="400">
                    Contamos con <strong>operarios calificados, legalmente habilitados y en constante
                        formación</strong>. Nos destacamos por nuestra <strong>innovación</strong>, <strong>atención
                        personalizada</strong> y <strong>comunicación clara</strong>, abordando cada proyecto con
                    compromiso, seguridad y eficiencia, con un enfoque especial en obras de gran escala o en altura.
                </p>
            </div>

            <div class="lg:w-1/2" data-aos="fade-up" data-aos-delay="200">
                <img src="@/assets/about.jpg" alt="Sobre Nosotros" class="border-2 border-accent rounded-lg w-full" />
            </div>
        </div>
    </section>
</template>
