// src/components/NavLink.tsx
interface NavLinkProps {
    href: string;
    label: string;
    active: boolean;
    onNavigate: () => void;
}

export default function NavLink({ href, label, active, onNavigate }: NavLinkProps) {
    return (
        <a href={href} onClick={onNavigate} className={[
            'pb-2 border-b-2 border-transparent transition-all duration-500 ease-in-out',
            active ? 'text-accent hover:border-accent' : 'text-light hover:text-accent hover:border-accent'
        ].join(' ')} aria-current={active ? 'page' : undefined}>
            {label}
        </a>
    );
}

// src/components/NavLink.vue
<script setup>
defineProps({
    href: String,
    label: String,
    active: Boolean,
});

const emit = defineEmits(['navigate']);
</script>

<template>
    <a :href="href" @click="emit('navigate')" :class="[
        'pb-2 border-b-2 border-transparent transition-all duration-500 ease-in-out',
        active ? 'text-accent hover:border-accent' : 'text-light hover:text-accent hover:border-accent'
    ]" :aria-current="active ? 'page' : null">
        {{ label }}
    </a>
</template>
