// src/components/ScrollToTop.tsx
import { useEffect, useState } from 'react';

// Scroll to top function
const scrollToTop = () => {
    window.scrollTo({
        top: 0,
        behavior: 'smooth',
    });
};

const ScrollToTop = () => {
    // Button visibility
    const [showButton, setShowButton] = useState(false);
    useEffect(() => {
        const handleScroll = () => {
            setShowButton(window.scrollY > 200);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    return (
        <button onClick={scrollToTop} style={showButton ? undefined : { display: 'none' }}
            className="bg-primary text-light fixed bottom-5 right-5 border-2 px-4 py-3 rounded-full hover:bg-accent transition duration-300 ease-in-out cursor-pointer"
            title="Ir arriba" aria-label="Scroll to top" aria-hidden={!showButton}>
            <i className="fas fa-arrow-up" aria-hidden="true" />
        </button>
    );
};

export default ScrollToTop;

// src/components/ScrollToTop.vue
<script setup>
import { ref, onMounted } from 'vue';

// Button visibility
const showButton = ref(false)
function handleScroll() {
    showButton.value = window.scrollY > 200
}
onMounted(() => {
    window.addEventListener('scroll', handleScroll)
})

// Scroll to top function
function scrollToTop() {
    window.scrollTo({
        top: 0,
        behavior: 'smooth',
    })
}
</script>

<template>
    <button v-show="showButton" @click="scrollToTop"
        class="bg-primary text-light fixed bottom-5 right-5 border-2 px-4 py-3 rounded-full hover:bg-accent transition duration-300 ease-in-out cursor-pointer"
        title="Ir arriba" aria-label="Scroll to top" :aria-hidden="!showButton">
        <i class="fas fa-arrow-up" aria-hidden="true" />
    </button>
</template>
