// src/App.tsx
import { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';
import Header from './components/Header';
import Hero from './components/Hero';
import About from './components/About';
import Services from './components/Services';
import Clients from './components/Clients';
import Contact from './components/Contact';
import Footer from './components/Footer';
import ScrollToTop from './components/ScrollToTop';

export default function App() {
    useEffect(() => {
        AOS.init({
            duration: 1500,
            once: true,
        });
    }, []);

    return (
        <>
            <Header />

            <main>
                <Hero />
                <About />
                <Services />
                <Clients />
                <Contact />
            </main>

            <Footer />

            <ScrollToTop />
        </>
    );
}

// src/App.vue
<script setup>
import AOS from 'aos';
import 'aos/dist/aos.css';
import { onMounted } from 'vue';
import Header from './components/Header.vue';
import Hero from './components/Hero.vue';
import About from './components/About.vue';
import Services from './components/Services.vue';
import Clients from './components/Clients.vue';
import Contact from './components/Contact.vue';
import Footer from './components/Footer.vue';
import ScrollToTop from './components/ScrollToTop.vue';

onMounted(() => {
    AOS.init({
        duration: 1500,
        once: true,
    });
});
</script>

<template>
    <Header />

    <main>
        <Hero />
        <About />
        <Services />
        <Clients />
        <Contact />
    </main>

    <Footer />

    <ScrollToTop />
</template>
